#!/usr/bin/env python

from SimpleSeer.base import *
from SimpleSeer.Session import Session

if (len(sys.argv) > 1):
   config_file = sys.argv[1] 
else:
   config_file = "../default.cfg"

Session(config_file)

from SimpleSeer.models.Frame import Frame

if not Session().retention:
  print "No retention policy set, skipping cleanup" 
  exit()

retention = Session().retention

while retention["interval"]:
  for f in Frame.objects(imgfile__ne = None).order_by('-capturetime').skip(retention['maxframes']):
    f.imgfile.delete()
    f.imgfile = None
    f.save(False)
  time.sleep(retention["interval"])


