#!/usr/bin/env python

from SimpleSeer.base import *
from SimpleSeer.Session import Session

if (len(sys.argv) > 1):
   config_file = sys.argv[1] 
else:
   config_file = "../default.cfg"

Session(config_file)

from SimpleSeer.Frame import Frame

if not Session().max_imagedata:
  print "No maximum number of images set, skipping cleanup" 
  exit()

max = Session().max_imagedata

for f in Frame.objects(imgfile__ne = None).order_by('-capturetime').skip(max):
  f.imgfile.delete()
  f.imgfile = None
  f.save(False)


